# Generated by Django 5.2.3 on 2025-06-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text='Unique identifier for the order', max_length=100, unique=True)),
                ('user', models.PositiveIntegerField(help_text='ID of the customer placing the order')),
                ('product', models.PositiveIntegerField(help_text='ID of the product being ordered')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product in the order')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price of the order', max_digits=10)),
                ('address', models.CharField(blank=True, help_text='Shipping address', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email of the customer', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Customer contact number', max_length=15, null=True)),
                ('city', models.CharField(blank=True, help_text='City of delivery', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State of delivery', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code for delivery', max_length=20, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('READY_TO_DISPATCH', 'Ready to Dispatch'), ('IN_TRANSIT', 'In Transit')], db_index=True, default='OPEN', help_text='Current status of the order', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the order was last updated')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_response', models.JSONField(blank=True, help_text='Parsed LLM response derived from the email', null=True)),
                ('email_message_id', models.CharField(blank=True, help_text='Unique Message-ID from the email header', max_length=255, null=True, unique=True)),
                ('email_subject', models.CharField(blank=True, help_text='Subject of the email', max_length=255, null=True)),
                ('email_from', models.EmailField(blank=True, help_text='Sender email address', max_length=254, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When the email was processed')),
                ('is_valid', models.BooleanField(default=False, help_text='True if LLM detected a valid status update')),
                ('order', models.ForeignKey(help_text='Associated order for which the email status was processed', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Order Status Logs',
                'ordering': ['-received_at'],
            },
        ),
    ]
