# Generated by Django 5.2.3 on 2025-06-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Associated order for which the email status was processed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_logs', to='orders.order'),
        ),
    ]
